from os import environ

SQLALCHEMY_DATABASE_URI=environ.get('SQLALCHEMY_DATABASE_URI')
SQLALCHEMY_TRACK_MODIFICATIONS=environ.get('SQLALCHEMY_TRACK_MODIFICATIONS')
SECRET_KEY=environ.get('SECRET_KEY')